seed: 0
torch_deterministic: false
device: cuda
epochs: 20
optimizer: Adam
optimizer_kwargs:
    lr: 0.001
data:
    files:
        # - /home/sunghwan/data/mobile_language_mapping/prepare_groceries/pick/all_static.pt
        # - /home/sunghwan/data/mobile_language_mapping/prepare_groceries/place/all_static.pt
        - /home/sunghwan/data/mobile_language_mapping/set_table/pick/all_static.pt
        # - /home/sunghwan/data/mobile_language_mapping/set_table/place/all_static.pt
        # - /home/sunghwan/data/mobile_language_mapping/tidy_house/pick/all_static.pt
        # - /home/sunghwan/data/mobile_language_mapping/tidy_house/place/all_static.pt
    clip_cache_files:
        # - /home/sunghwan/data/mobile_language_mapping/prepare_groceries/pick/all_static_clip.pt
        # - /home/sunghwan/data/mobile_language_mapping/prepare_groceries/place/all_static_clip.pt
        - /home/sunghwan/data/mobile_language_mapping/set_table/pick/all_static_clip.pt
        # - /home/sunghwan/data/mobile_language_mapping/set_table/place/all_static_clip.pt
        # - /home/sunghwan/data/mobile_language_mapping/tidy_house/pick/all_static_clip.pt
        # - /home/sunghwan/data/mobile_language_mapping/tidy_house/place/all_static_clip.pt
    load_clip_cache: true 
    valid_ratio: 0.1
    batch_size: 256
    num_workers: 16
    multiprocessing_context: fork
clip_model:
    model_name: EVA02-L-14
    model_pretrained: merged2b_s4b_b131k
voxel_hash_table:
    resolution: 0.12
    num_levels: 2
    level_scale: 2.0
    hash_table_size: 2097152  # 2**21
    voxel_feature_dim: 64
    scene_bound_min: [-2.6, -8.1, 0.0]
    scene_bound_max: [4.6, 4.7, 3.1]
depth_downsample_method: nearest-exact
decoder_hidden_dim: 768
decoder_output_dim: 768
output_dir: /home/sunghwan/data/results/mobile_language_mapping/static_mapping/nearest-exact
valid_interval: 1000
ckpt_interval: 1
test_model_dir: 
