cfg:
    seed: 0
    torch_deterministic: false
    device_clip: cuda:1
    device_decoder: cuda:0
    epochs: 30
    optimizer: Adam
    optimizer_kwargs:
        lr: 0.001
    data:
        files:
            - /home/daizhirui/Data/mobile_language_mapping/prepare_groceries/pick/all_static.pt
            - /home/daizhirui/Data/mobile_language_mapping/prepare_groceries/place/all_static.pt
            - /home/daizhirui/Data/mobile_language_mapping/set_table/pick/all_static.pt
            - /home/daizhirui/Data/mobile_language_mapping/set_table/place/all_static.pt
            - /home/daizhirui/Data/mobile_language_mapping/tidy_house/pick/all_static.pt
            - /home/daizhirui/Data/mobile_language_mapping/tidy_house/place/all_static.pt
        clip_cache_files:
            - /home/daizhirui/Data/mobile_language_mapping/prepare_groceries/pick/all_static_clip.pt
            - /home/daizhirui/Data/mobile_language_mapping/prepare_groceries/place/all_static_clip.pt
            - /home/daizhirui/Data/mobile_language_mapping/set_table/pick/all_static_clip.pt
            - /home/daizhirui/Data/mobile_language_mapping/set_table/place/all_static_clip.pt
            - /home/daizhirui/Data/mobile_language_mapping/tidy_house/pick/all_static_clip.pt
            - /home/daizhirui/Data/mobile_language_mapping/tidy_house/place/all_static_clip.pt
        load_clip_cache: true
        mask_out_classes: []
        build_config_names: [v3_sc1_staging_13.scene_instance.json]
        sensor_names: [fetch_hand, fetch_head]
        valid_ratio: 0.1
        batch_size: 32
        num_workers: 16
        multiprocessing_context: fork
    clip_model:
        model_name: EVA02-L-14
        model_pretrained: merged2b_s4b_b131k
    grid_cfg:
        name: grid_net
        spatial_dim: 3
        grid:
            type: regular
            feature_dim: 60
            init_stddev: 0.2
            bound:
                - [-2.6, 4.6]
                - [-8.1, 4.7]
                - [0.0, 3.1]
            base_cell_size: 0.4
            per_level_scale: 2.0
            n_levels: 2
            n_scenes: 440
            second_order_grid_sample: false
    depth_downsample_method: nearest
    decoder_hidden_dim: 240
    decoder_output_dim: 768
    output_dir: /home/daizhirui/results/mobile_language_mapping/static_mapping_per_episode/nearest
    valid_interval: 1000
    ckpt_interval: 1
    test_model_dir:
vertices_fp: null
min_depth: 0.0
max_depth: 50.0
frame_downsample_factor: 1
pcd_downsample_factor: 1
batch_size: 1048576
init_grid_map_id: 0
