seed: 2

eval_env:
  make_env: True
  env_id: "PickSubtaskTrain-v0"
  num_envs: 50
  max_episode_steps: 200
  all_plan_count: 244
  continuous_task: True
  cat_state: True
  cat_pixels: False
  frame_stack: 1
  stationary_base: False
  stationary_torso: False
  stationary_head: True
  task_plan_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/set_table/pick/train/all_10.json
  spawn_data_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/set_table/pick/train/spawn_data.pt
  record_video: False
  info_on_video: True
  extra_stat_keys: []
  env_kwargs:
    robot_force_mult: 0.001
    robot_force_penalty_min: 0.2
    target_randomization: False

algo:
  name: "bc"
  lr: 1e-5
  batch_size: 8
  epochs: 10
  eval_freq: 1
  log_freq: 1
  save_freq: 1
  trajs_per_obj: "all"
  data_dir_fp: null
  max_cache_size: 0
  save_backup_ckpts: False
  torch_deterministic: True

  # Pretrained model paths
  static_map_path: "pretrained/hash_voxel_sparse.pt"
  implicit_decoder_path: "pretrained/implicit_decoder.pt"

  # CLIP / Agent Settings
  clip_input_dim: 768
  open_clip_model_name: "EVA02-L-14"
  open_clip_model_pretrained: "merged2b_s4b_b131k"
  text_input: ["bowl", "apple"]
  camera_intrinsics: [71.9144, 71.9144, 112, 112]
  cos_loss_weight: 0.1
  bc_loss_weight: 10.0
  action_temp_weights: 0.3
  
  # Transformer architecture
  num_heads: 8
  hidden_dim: 512
  num_layers_transformer: 4
  num_action_layer: 6
  action_pred_horizon: 16
  transf_input_dim: 768
  neighbor_k: 512

logger:
  workspace: mshab_exps
  exp_name: bc-pick
  clear_out: True
  tensorboard: True
  wandb: False
