seed: 0

eval_env:
  make_env: True

  env_id: "PlaceSubtaskTrain-v0"
  num_envs: 50
  max_episode_steps: 200
  all_plan_count: 519
 
  continuous_task: True

  cat_state: True
  cat_pixels: False
  frame_stack: 1

  stationary_base: False
  stationary_torso: False
  stationary_head: True

  task_plan_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/set_table/place/train/all.json
  spawn_data_fp: "~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/set_table/place/train/spawn_data.pt"

  record_video: False
  info_on_video: True

  extra_stat_keys: []

  env_kwargs:
    robot_force_mult: 0.001
    robot_force_penalty_min: 0.2
    target_randomization: False

algo:
  name: bc

  lr: 3e-4
  batch_size: 8
  epochs: 2

  eval_freq: 1
  log_freq: 1
  save_freq: 1

  trajs_per_obj: all
  data_dir_fp: null
  max_cache_size: 0

  save_backup_ckpts: False

  # Determinism
  torch_deterministic: True

  # CLIP / Agent Settings
  clip_input_dim: 768
  open_clip_model_name: "EVA02-L-14"
  open_clip_model_pretrained: "merged2b_s4b_b131k"
  text_input: ["tomato_soup_can", "cracker_box", "tuna_fish_can", "bowl", "sugar_box", "master_chef_can", "pudding_box", "potted_meat_can", "gelatin_box"]
  camera_intrinsics: [71.9144, 71.9144, 112, 112]
  state_mlp_dim: 128

  # Pre-trained Weights
  # pretrained_agent_path:  "/home/sunghwan/workspace/mobile_language_mapping/mshab_exps/PickSubtaskTrain-v0/set_table-rcad-bc-point-pick/bc-pick-all-local-trajs_per_obj=1000/models/stage1-final_agent.pt"


logger:
  workspace: mshab_exps
  exp_name: bc-pick
  clear_out: True
  
  tensorboard: True
  wandb: False
