seed: 0
task: tidy_house
save_trajectory: False

eval_env:
  make_env: True

  env_id: "SequentialTask-v0"
  num_envs: 252
  max_episode_steps: 200
 
  continuous_task: True

  cat_state: True
  cat_pixels: False
  frame_stack: 3

  stationary_base: False
  stationary_torso: False
  stationary_head: True

  task_plan_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/tidy_house/pick/train/all.json

  record_video: False
  info_on_video: True

  extra_stat_keys: []

  env_kwargs:
    require_build_configs_repeated_equally_across_envs: False
    add_event_tracker_info: True
    task_cfgs:
      navigate:
        ignore_arm_checkers: True

logger:
  workspace: mshab_exps
  exp_name: eval_seq_task
  clear_out: True
  
  tensorboard: True
  wandb: False
